In [2]:
import numpy as np
import pandas as pd
import pickle

In [7]:
ranking_df = pd.read_csv('sushi3b.5000.10.score', sep=' ', header=None)

In [8]:
ranking_df

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
0     -1   0  -1   4   2  -1  -1  -1  -1  -1  ...  -1  -1  -1  -1  -1  -1  -1   
1     -1  -1  -1  -1  -1  -1   0  -1   1  -1  ...  -1  -1  -1  -1  -1  -1  -1   
2     -1   3   4  -1  -1  -1   3  -1  -1  -1  ...  -1  -1  -1  -1  -1  -1  -1   
3      4  -1  -1   3   4   1  -1  -1   4   3  ...  -1  -1  -1  -1  -1  -1  -1   
4     -1  -1  -1  -1   1  -1  -1  -1  -1   4  ...  -1  -1  -1  -1  -1  -1  -1   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
4995  -1  -1  -1   4  -1  -1   4  -1   4  -1  ...  -1  -1  -1  -1  -1  -1  -1   
4996   3   4   2  -1   1   4  -1  -1   4  -1  ...  -1  -1  -1  -1  -1  -1  -1   
4997   3  -1  -1  -1  -1  -1  -1   3  -1  -1  ...  -1  -1  -1  -1  -1  -1  -1   
4998  -1   4   4   4   0  -1  -1  -1  -1   4  ...  -1  -1  -1  -1  -1  -1  -1   
4999  -1  -1   3   4   4  -1  -1  -1   4   4  ...  -1  -1  -1  -1  -1  -1  -1   

      97  98  99  
0     -1  -1  -1  
1     -1  -1  -1  
2     -1  -1  -1  
3     -1  -1  -1  
4     -1  -1   0  
...   ..  ..  ..  
4995  -1  -1  -1  
4996  -1  -1  -1  
4997  -1  -1  -1  
4998  -1  -1  -1  
4999  -1  -1  -1  

[5000 rows x 100 columns]

In [24]:
ranking_arr = ranking_df.to_numpy() + 1

In [32]:
numnonzero_arr = np.count_nonzero(ranking_arr, axis=0)

In [34]:
numnonzero_arr

array([1546, 1535, 1406, 1457, 1380, 1447, 1412, 1353, 1321, 1244, 1297,
       1213, 1194, 1118, 1112, 1077, 1012, 1016,  968,  957,  939,  945,
        868,  857,  841,  847,  785,  775,  699,  694,  696,  619,  512,
        567,  560,  545,  500,  532,  509,  453,  433,  468,  413,  334,
        336,  327,  358,  366,  347,  348,  355,  385,  287,  282,  231,
        199,  214,  218,  219,  236,  219,  234,  213,  215,  234,  155,
        142,  138,  135,  155,  141,  164,  169,  133,  165,  148,  144,
        131,  150,  153,   78,   67,   88,   50,   66,   80,   52,   77,
         85,   84,   74,   80,   76,   75,   72,   95,   68,   79,   75,
         77])

In [30]:
sumrank_arr = np.sum(ranking_arr, axis=0)

In [35]:
sumrank_arr

array([6498, 6208, 6095, 5706, 4913, 5381, 5568, 5161, 5857, 5328, 5215,
       4996, 4012, 4432, 4079, 4449, 3301, 3007, 3257, 4269, 3845, 3611,
       3628, 2852, 2681, 3220, 3228, 3014, 2158, 2332, 2349, 2344, 1733,
       1830, 2023, 1773, 1876, 2340, 1737, 1535, 1332, 1930, 1277, 1336,
       1229, 1202, 1283, 1575, 1194, 1037, 1279, 1248,  893, 1170,  796,
        639,  616,  832,  747,  657,  688, 1001,  738,  715,  732,  571,
        469,  455,  433,  457,  487,  618,  611,  499,  565,  497,  570,
        385,  448,  641,  236,  191,  288,  158,  204,  252,  145,  236,
        334,  244,  192,  260,  221,  211,  201,  344,  247,  168,  236,
        231])

In [36]:
meanrank_arr = sumrank_arr / numnonzero_arr

In [144]:
inter1 = meanrank_arr - np.min(meanrank_arr)

In [145]:
inter2 = inter1 * (9 / np.max(inter1) )

In [146]:
scaledrank_arr = inter2 - 4

In [147]:
scaledrank_arr

array([ 4.00635773,  3.39405975,  4.51487296,  2.90040703,  1.5273253 ,
        2.13876873,  3.00480462,  2.5079784 ,  4.8956939 ,  4.31424507,
        3.30351967,  3.68097558,  0.75615186,  3.08530706,  1.94381541,
        3.72803497,  0.37723221, -0.78799363,  0.77363887,  5.        ,
        3.58870104,  2.53372529,  3.91620753,  0.63182227,  0.09196711,
        2.45849708,  3.65548189,  2.79540191, -0.29592758,  0.7565241 ,
        0.81347004,  2.40104755,  0.85112293,  0.24481169,  1.72918848,
        0.34389351,  2.26705258,  4.75972008,  0.95834122,  0.86560226,
       -0.33855207,  3.7010932 , -0.27764344,  3.22325542,  1.90361104,
        1.97340955,  1.61852683,  4.3925939 ,  1.06764337, -0.7099575 ,
        1.69185378,  0.29896521, -0.2025022 ,  3.79750215,  1.08678769,
        0.18135548, -1.10084545,  2.51579549,  0.95211522, -1.46561512,
       -0.08662331,  4.29427114,  1.15966456,  0.62292887, -0.13808624,
        2.00437043,  0.5351568 ,  0.51311998,  0.16729055, -0.83

In [224]:
fvals = scaledrank_arr

In [228]:
pickle.dump(fvals, open("fvals.p", "wb"))

In [148]:
zipped = list(zip(scaledrank_arr, range(100)))

In [149]:
fval_idx = sorted(zipped, reverse=True)

In [150]:
fval_idx

[(5.0, 19),
 (4.895693902126329, 8),
 (4.759720082185915, 37),
 (4.51487295961271, 2),
 (4.392593898267295, 47),
 (4.314245069918266, 9),
 (4.294271143221419, 61),
 (4.006357731095532, 0),
 (3.954066148346291, 79),
 (3.9162075279915234, 22),
 (3.7975021475526916, 53),
 (3.728034974613098, 15),
 (3.701093203439142, 41),
 (3.6809755765998675, 11),
 (3.6554818919335927, 26),
 (3.5887010396625056, 20),
 (3.3940597504606362, 1),
 (3.303519665670656, 10),
 (3.223255418614534, 43),
 (3.0853070605256336, 13),
 (3.062603059923502, 76),
 (3.0048046192612876, 6),
 (2.9510914227144305, 88),
 (2.900407027229946, 3),
 (2.795401911081255, 27),
 (2.5337252949628635, 21),
 (2.51579549043384, 57),
 (2.507978398101022, 7),
 (2.4584970830274697, 25),
 (2.4010475473169706, 31),
 (2.3298715702839123, 71),
 (2.2670525796855063, 36),
 (2.2665887412965056, 73),
 (2.138768729123168, 5),
 (2.0043704262232156, 65),
 (1.973409545495307, 45),
 (1.943815410909692, 14),
 (1.9036110436524805, 44),
 (1.8057346066348332

In [168]:
diff = fval_idx[96][0] - fval_idx[97][0]

In [169]:
1 /(1 + np.exp(-diff))

0.5043984517673543

In [170]:
pickle.dump(fval_idx, open("fval_idx_tuples.p", "wb"))

In [210]:
sushi_df = pd.read_csv('sushi3.idata', sep='\t', header=None)

In [211]:
sushi_df = sushi_df.drop(columns=[0, 1, 4])

In [213]:
sushi_df.columns = range(sushi_df.shape[1])

In [214]:
sushi_df

0  1         2         3         4     5
0   1  0  2.728978  2.138422  1.838420  0.84
1   1  0  0.926384  1.990228  1.992459  0.88
2   1  0  1.769559  2.348506  1.874725  0.88
3   1  0  2.688401  2.043240  1.515152  0.92
4   1  0  0.813043  1.643478  3.287282  0.88
.. .. ..       ...       ...       ...   ...
95  1  0  2.600000  1.094737  1.000000  0.04
96  1  0  1.970588  1.000000  1.000000  0.04
97  1  0  1.936709  0.443038  1.500000  0.04
98  1  0  2.160000  0.613333  1.000000  0.04
99  1  0  1.779221  0.727273  1.250000  0.04

[100 rows x 6 columns]

In [215]:
sushi_arr = sushi_df.to_numpy()

In [216]:
sushi_arr[:, 2] *= 1/4

In [217]:
sushi_arr[:, 3] *= 1/3

In [218]:
sushi_arr[:, 4] -= np.min(sushi_arr[:, 4])
sushi_arr[:, 4] *= 1/np.max(sushi_arr[:, 4])

In [219]:
sushi_arr[:, 4]

array([0.24054823, 0.28474297, 0.25096426, 0.14780038, 0.65623633,
       0.11026686, 0.4864108 , 0.00931515, 1.        , 0.265381  ,
       0.22154805, 0.36185926, 0.66919521, 0.193105  , 0.75927013,
       0.14683135, 0.39500377, 0.24575436, 0.13854733, 0.62188977,
       0.59365452, 0.3102359 , 0.2977743 , 0.01504755, 0.32276995,
       0.3549745 , 0.16635903, 0.41929467, 0.42438272, 0.00573813,
       0.00521648, 0.13335845, 0.09780908, 0.37113111, 0.48438781,
       0.23908885, 0.28939066, 0.42259731, 0.        , 0.23510404,
       0.00956355, 0.58743407, 0.11487133, 0.        , 0.14241002,
       0.05738132, 0.61206747, 0.69292297, 0.01147626, 0.3347244 ,
       0.04590506, 0.12815163, 0.20083464, 0.46567988, 0.14664116,
       0.14345331, 0.04781777, 0.09563554, 0.0836811 , 0.21517997,
       0.        , 0.39078744, 0.29733959, 0.28690662, 0.39848142,
       0.38254217, 0.24387063, 0.1673622 , 0.43035994, 0.        ,
       0.        , 0.        , 0.07172666, 0.17931664, 0.     

In [221]:
for i in range(6):
    print(np.max(sushi_arr[:, i]))

1.0
1.0
0.93263688760807
0.7828354670459932
0.9999999999999999
0.92


In [223]:
sushi_arr.shape

(100, 6)

In [229]:
pickle.dump(sushi_arr, open("sushi_features.p", "wb"))